/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package location;

import javax.swing.JOptionPane;
import model.Locataire;

/**
 *
 * @author pak
 */
public class EnregistrementLocataireUI extends javax.swing.JFrame {
  String sql="";
  boolean status=false;
  
    /**
     * Creates new form EnregistrementLocataireUI
     */
    public EnregistrementLocataireUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        nomL.setText(null);
        prenomL.setText(null);
        villeL.setSelectedIndex(0);
        sexeL.setSelectedIndex(0);
        natioL.setSelectedIndex(0);
        emailL.setText(null);
        telL.setText(null);
        pwdL.setText(null);
        cniL.setText(null);
        pwdL.setVisible(false);
        pass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomL = new javax.swing.JTextField();
        prenomL = new javax.swing.JTextField();
        emailL = new javax.swing.JTextField();
        telL = new javax.swing.JTextField();
        pwdL = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        sexeL = new javax.swing.JComboBox<>();
        villeL = new javax.swing.JComboBox<>();
        cniL = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        natioL = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomL.setText("jTextField1");
        getContentPane().add(nomL, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 80, 280, 29));

        prenomL.setText("jTextField2");
        getContentPane().add(prenomL, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 80, 240, 29));

        emailL.setText("jTextField3");
        emailL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailLActionPerformed(evt);
            }
        });
        getContentPane().add(emailL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 280, 30));

        telL.setText("jTextField4");
        getContentPane().add(telL, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 240, 30));

        pwdL.setText("jPasswordField1");
        getContentPane().add(pwdL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 124, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 47, 700, 10));

        sexeL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        sexeL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexeLActionPerformed(evt);
            }
        });
        getContentPane().add(sexeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 240, 30));

        villeL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Douala", "Yaoundé", "Maroua", "Ngaroundéré", "Bertoua", "Ndschang", "Batourie", "Abong-bang" }));
        getContentPane().add(villeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 230, 30));

        cniL.setText("jTextField5");
        getContentPane().add(cniL, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 323, 280, 30));

        pass.setText("Password");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Téléphone");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Sexe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Cni");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 40, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Nationnalité");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Prénom");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("S'enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 130, 30));

        natioL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camerounais(e)", "Canadien(ne)", "Nigériane", "Ghana", "Français", "Italienne", "Marocain" }));
        natioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natioLActionPerformed(evt);
            }
        });
        getContentPane().add(natioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 230, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("ville");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 30, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enregistrement d'un locataire");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 760, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailLActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Locataire l=new Locataire(nomL.getText(), prenomL.getText(), sexeL.getSelectedItem().toString(), telL.getText(),emailL.getText(), natioL.getSelectedItem().toString(), cniL.getText(), pwdL.getText(), villeL.getSelectedItem().toString());
         status= l.saveLocataire();
         if(status){
            JOptionPane.showMessageDialog(null, "Enregistrement du locataire "+nomL.getText()+" "+prenomL.getText()+" effectuer avec succes !");
//        ConnexionUI loginui=new ConnexionUI();
//        loginui.setVisible(true);
          
//            new tableaubayeur().setVisible(true);

        this.setVisible(false);
         }else{
             
         }
             
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sexeLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexeLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexeLActionPerformed

    private void natioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natioLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_natioLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrementLocataireUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrementLocataireUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrementLocataireUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrementLocataireUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnregistrementLocataireUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cniL;
    private javax.swing.JTextField emailL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> natioL;
    private javax.swing.JTextField nomL;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField prenomL;
    private javax.swing.JPasswordField pwdL;
    private javax.swing.JComboBox<String> sexeL;
    private javax.swing.JTextField telL;
    private javax.swing.JComboBox<String> villeL;
    // End of variables declaration//GEN-END:variables
}
